bakery/bakery/urls.py
from django.contrib import admin
from django.urls import path,include

from store_app.views import *

from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('store_app.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),  # Add this line for default authentication views
    #path('user/',include('userauths.urls')),
    #path('search/',search,name='search'),

  
] 


urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bakery/store_app/urls.py
from django.urls import path
#from . import views
from .views import *
from django.contrib import admin

# from django.conf import settings
# from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from django.contrib.auth.views import ( 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView, 
    PasswordResetCompleteView 
)


urlpatterns = [
   
    path('',base,name='base'),
    path('',hf,name='hf'),
    path('item/', item, name='item'),
    path('category/',category,name='category'),
    path('home/', home, name='home'),
    path('gallary/', gallary, name='gallary'),
    path('about/', about, name='about'),
    path('contact/', Contact_Page, name='contact'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),

    path('search/',search,name='search'),
    path('search/<str:id>',product_details,name='product_details'),
    path('item/<str:id>',product_details,name='product_details'),
    #path('submit/<int:id>',submit_review,name=submit_review),
    #path('submit_review/<int:item_id>', submit_review, name='submit_review'),
    #path('view_reviews/<int:item_id>/', view_reviews, name='view_reviews'),
    path('add_review/<int:id>',add_review, name='add_review'),
    
    path('wishlist/add/<int:item_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:item_id>/', remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/', wishlist, name='wishlist'),

    # for cart
    path('cart/add/<int:id>/', cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',item_decrement, name='item_decrement'),
    path('cart/cart_clear/', cart_clear, name='cart_clear'),
    path('cart/cart-detail/',cart_detail,name='cart_detail'),
    

    path('cart/checkout/', Check_out, name='checkout'),
    path('cart/checkout/placeorder', Place_Order, name='place_order'),
    path('success/',success,name='success'),
    path('cart/cart_view/',cart_view,name='cart_view'),
    # path('cart/checkout/cart_view/',checkout_view,name='checkout_view'),

    path('Your_Order', Your_Order, name='your_order'),
    path('generateinvoice/<int:order_id>/', generate_invoice, name = 'generateinvoice'),
    #for profile

    # path('profile/', profile, name='profile'),
    # path('edit/', profile_edit, name='edit'),

    path('profile-update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # for forgot password

    #path('forgotpassword/', forgotpassword, name='forgotpassword'),
    #path('ChangePassword/', Change_Password, name='ChangePassword'),

    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='forgot/forgotpassword.html'),name='password_reset'), 
    path('password_reset_done/',auth_views.PasswordResetDoneView.as_view(template_name='forgot/pass_reset_done.html'),name='password_reset_done'), 
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='forgot/confirm_password.html'),name='password_reset_confirm'), 
    path('password_reset_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='forgot/pass_reset_complete.html'),name='password_reset_complete'),


]

bakery/store_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

from django.db.models.signals import post_save
from django.dispatch import receiver
# from .models import UserProfile

from ckeditor.fields import RichTextField

from django.forms import ValidationError
#from django.utils import timezone
# Create your models here.
"""
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, related_name='Profile')
    image= models.ImageField(upload_to='Item_images/img', default='default.svg')
    phone = models.IntegerField(null=True)
    address=models.TextField(null=True)
    

    def __str__(self):
        return f'{self.user} Profile'
"""

class Categories(models.Model):
    name=models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def clean(self):
        existing_category = Categories.objects.filter(name=self.name)
        if self.pk:
            existing_category = existing_category.exclude(pk=self.pk)
        if existing_category.exists():
            raise ValidationError("Category with this name already exists.")


  
class Flavour(models.Model):
    name=models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Filter_Price(models.Model):
    FILTER_PRICE=(
        ('10 To 200','10 To 200'),
        ('200 To 500','200 To 500'),
        ('500 To 1000','500 To 1000'),
        ('1000 To 1500','1000 To 1500'),
        ('1500 To 2000','1500 To 2000'),
        ('2000 To 5000','2000 To 5000'),
    )    

    price=models.CharField(choices=FILTER_PRICE,max_length=60)

    def __str__(self):
        return self.price

class Item(models.Model):
    STOCK=('IN STOCK','IN STOCK'),('OUT OF STOCK','OUT OF STOCK')
    INGREDIENTS=('WITH EGG','WITH EGG'),('WITHOUT EGG','WITHOUT EGG')
    STATUS=('Publish','Publish'),('Draft','Draft')

    unique_id=models.CharField(unique=True,max_length=200,null=True,blank=True)
    image=models.ImageField(upload_to='Item_images/img')
    name=models.CharField(max_length=200)
    price=models.IntegerField()
    information=RichTextField(null=True)
    description=RichTextField(null=True)
    stock=models.CharField(choices=STOCK,max_length=200)
    ingredients=models.CharField(choices=INGREDIENTS,max_length=200)
    status=models.CharField(choices=STATUS,max_length=200)  
    created_date=models.DateTimeField(default=timezone.now)


    categories=models.ForeignKey(Categories,on_delete=models.CASCADE)
    flavour=models.ForeignKey(Flavour, on_delete=models.CASCADE) 
    filter_price=models.ForeignKey(Filter_Price, on_delete=models.CASCADE)

    def clean(self):
        existing_item = Item.objects.filter(name=self.name)
        if self.pk:
            existing_item = existing_item.exclude(pk=self.pk)
        if existing_item.exists():
            raise ValidationError("Item with this name already exists.")


    

    def save(self,*args,**kwargs):
        if self.unique_id is None and self.created_date and self.id:
            self.unique_id=self.created_date.strftime('75%Y%m%d23') + str(self.id)
        return super().save(*args,**kwargs)   
    

    def __str__(self):
         return self.name
  


    

class Contact_us(models.Model):
    name = models.CharField(max_length=200)       
    email = models.EmailField(max_length=200)
    phone = models.IntegerField()
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email    


class Order(models.Model):
    user= models.ForeignKey(User,on_delete=models.CASCADE)  
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    email=models.EmailField(max_length=100)
    phone=models.IntegerField(null=True)
    address=models.TextField()
    city=models.CharField(max_length=100)
    state=models.CharField(max_length=100)
    pin=models.IntegerField() 
    #amount=models.IntegerField(null=True)
    amount=models.CharField(max_length=100,null=True)
    payment_id=models.CharField(max_length=200,null=True,blank=True)
    paid=models.BooleanField(default=False,null=True)
    date=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class OrderItem(models.Model):
    PROCESS = ('PENDING','PENDING'),('IN PROCESS','IN PROCESS'),('MADE','MADE')
    item=models.ForeignKey(Item,on_delete=models.CASCADE,null=True)
    user= models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    item=models.CharField(max_length=200)
    image=models.ImageField(upload_to='Item_images/img')
    quantity=models.CharField(max_length=20)
    price=models.CharField(max_length=50)
    process=models.CharField(choices=PROCESS,max_length=200,default='PENDING',null=False)
    total=models.CharField(max_length=100)

    def __str__(self):
        return self.item


class Review(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField()  # Rating can be on a scale of 1-5
    review = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.review


class Coupon(models.Model):
    code = models.CharField(max_length=50, unique=True)
    discount_percentage = models.FloatField()
    valid_from = models.DateField()
    valid_to = models.DateField()
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.code


class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    phone=models.IntegerField(null=False,default='0')
    address=models.TextField(max_length=200,null=False,default='')
    city=models.CharField(max_length=100,null=False,default='')
    state=models.CharField(max_length=100,null=False,default='')
    pin=models.IntegerField(default='0') 


    def _str_(self):
        return self.user.username

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # bio = models.TextField(max_length=500, blank=True)
    
    phone = models.CharField(max_length=12, blank=True)
    # birth_date = models.DateField(null=True, blank=True)
    address=models.CharField(max_length=12, blank=True)
    profile_image = models.ImageField(default='client1.jpg', upload_to='profile_images/', null=True, blank=True)

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()




class Wishlist(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    item=models.ForeignKey(Item,on_delete=models.CASCADE)




"""
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE, related_name="profile")
    is_email_verified=models.BooleanField(default=False)
    email_token=models.CharField(max_length=100,null=True,blank=False)
    profile_image=models.ImageField(upload_to='Item_images/img',null=True)

    def get_cart_count(self):
        return request.session.cart|length

def get_file_path(instance,filename):
     return f"uploads/{filename}"
"""

bakery/store_app/forms.py
from django import forms
from .models import *

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username', 
            'first_name', 
            'last_name', 
            'email', 
        ]

class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = [
            # 'bio',
            'user',
            'phone',
            # 'birth_date',
            'address',
            'profile_image'
        ]



class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'rating']



"""
class EditUserProfileForm(UserChangeForm):
    password=None
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','phone','address']
        labels = {'email':'Email'}
        
class EditAdminProfileForm(UserChangeForm):
    password=None
    class Meta:
        model = User
        fields = '__all__'
        labels = {'email':'Email'}
"""

bakery/bakery/views.py
"""
from django.shortcuts import render,redirect
from bakery.models import item

def BASE(request):
    return render(request, 'base.html')


def REGISTER(request):
    return render(request, 'auth.html')
"""

bakery/templates/profiles/profil.html
{% extends 'hf.html'%}
{% block content %}
{% load static %}

 


<head>
  <style>
    /* Style for container-fluid */
.container-fluid {
    padding: 20px;
}

/* Style for headings */
h1 {
    font-size: 24px;
    color: #333;
}

/* Style for alerts */
.alert {
    margin-bottom: 10px;
    padding: 10px;
    border-radius: 5px;
}

.alert-success {
    background-color: #d4edda;
    border-color: #c3e6cb;
    color: #155724;
}

/* Style for card */
.card {
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

.card-body {
    padding: 20px;
}

/* Style for profile image */
.profile-image {
    border-radius: 50%;
}

/* Style for profile information */
.profile-info {
    margin-bottom: 20px;
}

.profile-info strong {
    font-weight: bold;
}

/* Style for update profile button */
.update-profile-btn {
    display: inline-block;
    padding: 10px 20px;
    background-color: #007bff;
    color: #fff;
    border-radius: 5px;
    text-decoration: none;
    transition: background-color 0.3s ease;
}

.update-profile-btn:hover {
    background-color: #0056b3;
}

</style>
</head>
<body>
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
        <h1 class="h3 mb-0 text-gray-800">Profile</h1>
        </div>          

        {% if messages %}
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
          {% endfor %}
        {% endif %}

        <!-- Main Content Here -->
        <div class="row">
          <div class="col-lg-2"></div>
          <div class="col-lg-3 my-5">
            <img src="{{user.userprofile.profile_image.url}}" class="rounded float-right" height="300px" width="300px">
          </div>
          <div class="card o-hidden border-0 shadow-lg my-5 col-lg-5">
            <div class="card-body">  
                <p><strong>Firstname: </strong> {{user.first_name}} </p>
                <p><strong>Lastname: </strong> {{user.last_name}} </p>
                <p><strong>Username: </strong> {{user.username}} </p>
                <p><strong>Email: </strong> {{user.email}} </p>
                
                <!-- <p><strong>Phone Number: </strong> {{UserProfile.phone}} </p>
                <p><strong>Address: </strong> {{user.userprofile.address}} </p> -->
                <a href="{% url 'profile-update' %}" class="btn btn-sm btn-primary shadow-sm">Update Profile</a>
            </div>
          </div>
        </div>



    </div>
    <!-- /.container-fluid -->

  </body>
{% endblock content %}

bakery/templates/profiles/profile-update.html
{% block content %}
{% load static %}
<head>

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
<link href="path/to/bootstrap.min.css" rel="stylesheet">

<style>
.body{
  border:2px solid #935f23;
}
/* Custom CSS */
input[type="text"],
input[type="email"],
input[type="file"],
button {
    width: 100%;
    padding: 10px;
    margin-bottom: 10px;
    border: 1px solid #ced4da;
    border-radius: 5px;
    box-sizing: border-box;
}

.button[type="submit"] {
    background-color: #935f23;
    color: #fff;
    cursor: pointer;
}

.button:hover {
    background-color: #bd813d;
}

.text-center {
    text-align: center;
}


</style>
</head>
  
<body>
  
  
  <!-- Begin Page Content -->
  <div class="container-fluid">

      <!-- Page Heading -->
      <!-- <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
      <h1 class="h3 mb-0 text-gray-800">Profile Update</h1>
      </div>           -->

      <!-- Main Content Here -->
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Edit Your Profile!..</h1>
                </div>
                <form method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{user_form}}
                  {{profile_form}}
                  <button type="submit" class="btn-success btn-block" style="background-color: #935f23;">Change Profile</button>
                </form>
                <hr>
                <div class="text-center">
                  <a class="small" href="{% url 'home' %}" style="color: #935f23;">Back</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
  <!-- /.container-fluid -->
</body>


{% endblock content %}

bakery/templates/profiles/profile-update1.html
{% block content %}
{% load static %}

<link href="{% static 'profile_edit.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link href="/static/css/profile_edit.css" rel="stylesheet">
<style>
	input{
		width:auto;
	}
</style>
<div class="container">
	
		<div class="main-body">
			<!-- Breadcrumb -->
			<nav aria-label="breadcrumb" class="main-breadcrumb">
				<ol class="breadcrumb">
				  <li class="breadcrumb-item">
					<a href="{% url 'home' %}">Home</a>
				  </li>
				  <!--
				  <li class="breadcrumb-item"><a href="javascript:void(0)">User</a></li>-->
				  
					<li class="breadcrumb-item">
					  <a href="{% url 'profile' %}">Profile</a>
					</li>
				  
				  <li class="breadcrumb-item active" aria-current="page">Edit</li>
				  
				</ol>
			  </nav>
			  <!-- /Breadcrumb -->
			<form method="POST" enctype="multipart/profile.html">
				{% csrf_token %}
				<div class="row">
					<div class="col-lg-4">
						<div class="card">
							<div class="card-body">
								<div class="d-flex flex-column align-items-center text-center">
									<img src="/static/images/user.jpg" alt="Admin" class="rounded-circle p-1" width="110">
									<div class="mt-3">
										<h4>{{curr_user.fname}}</h4>
										<!--<p class="text-secondary mb-1">Full Stack Developer</p>-->
										<!--<p class="text-muted font-size-sm">Bay Area, San Francisco, CA</p>-->
										<button class="btn btn-primary">Chaange photo</button>
										<!--<button class="btn btn-outline-primary">Message</button>-->
									</div>
								</div>
								
							</div>
						</div>
					</div>
					
					
					<div class="col-lg-8">
						<div class="card" style="width:max-content">
							<div class="card-body">
								<table class="table">
									<tbody>
										<tr>
											<th scope="row">Full Name</th>
											<td><input type="text" class="form-control" name="firstname"  style="width:auto" value="{{ curr_user.fname }}"></td>
										</tr>
										<tr>
											<th scope="row">First Name</th>
											<td><input type="text" class="form-control" name="firstname"  style="width:auto" value="{{ curr_user.fname }}"></td>
										</tr>
										<tr>
											<th scope="row">Last Name</th>
											<td><input type="text" class="form-control" name="lastname" value="{{ curr_user.lname }}"></td>
										</tr>
										<!--
										<tr>
											<th scope="row">Gender</th>
											<td>
												<div class="custom-control custom-radio custom-control-inline">
													<input type="radio" id="customRadioInline1" name="gender" class="custom-control-input" value="Male" {% if curr_user.gender == 'Male' %} checked {% endif %}>
													<label class="custom-control-label" for="customRadioInline1">Male</label>
												</div>
												<div class="custom-control custom-radio custom-control-inline">
													<input type="radio" id="customRadioInline2" name="gender" class="custom-control-input" value="Female" {% if curr_user.gender == 'Female' %} checked {% endif %}>
													<label class="custom-control-label" for="customRadioInline2">Female</label>
												</div>
											</td>
										</tr>
										-->
										<tr>
											<th scope="row">Email</th>
											<td><input type="text" class="form-control" name="email" value="{{ user.email }}"></td>
										</tr>
										<tr>
											<th scope="row">Phone</th>
											<td><input type="text" class="form-control" name="phone" value="{{ user.phone }}"></td>
										</tr>
										<tr>
											<th scope="row">Address</th>
											<td><input type="textarea" class="form-control" name="phone" value="{{ curr_user.phone }}"></td>
										</tr>
										<tr>
											<td colspan="2" class="text-center">
												<!-- <input type="submit" class="btn btn-primary px-4" value="Save Changes"> -->
												<button type="submit" class="btn btn-success btn-block">Update</button>
											</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>

{%endblock%}

bakery/templates/profiles/profile-update3.html
{% block content %}
{% load static %}
<head>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
<link href="path/to/bootstrap.min.css" rel="stylesheet">

<style>
  
    /* Custom CSS */
    input[type="text"],
    input[type="email"],
    input[type="file"],
    button {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ced4da;
        border-radius: 5px;
        box-sizing: border-box;
    }

    button {
        background-color: #28a745;
        color: #fff;
        cursor: pointer;
    }

    button:hover {
        background-color: #218838;
    }

    .text-center {
        text-align: center;
    }


</style>
</head>

<body>
  
 
    <!-- Begin Page Content -->
    <div class="container-fluid">

      <!-- Page Heading -->
      <!-- <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
      < <h1 class="h3 mb-0 text-gray-800">Profile Update</h1> ->
      </div>           -->

      <!-- Main Content Here -->
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Update Your Profile!</h1>
                </div>
                <form method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <!-- <input type="hidden" name="csrfmiddlewaretoken" value="sVp2P2CNyZdtMpcoqEhfsfrAtOGaGfRhPwXZmlF02XSeoAylLMHzwtwWV9dL1dqc"> -->
                  <div>
    <label for="id_username">Username:</label>

    <!-- <div class="helptext" id="id_username_helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</div> -->

    <input type="text" name="username"  maxlength="150" required aria-describedby="id_username_helptext" id="id_username">

    </div>

    <div>
    <label for="id_first_name">First name:</label>



    <input type="text" name="first_name"  maxlength="150" id="id_first_name">

    </div>

    <div>
    <label for="id_last_name">Last name:</label>



    <input type="text" name="last_name"  maxlength="150" id="id_last_name">

    </div>

    <div>
    <label for="id_email">Email address:</label>



    <input type="email" name="email"  maxlength="254" id="id_email">



    </div>
                  <div>
    <label for="id_phone">Phone:</label>



    <input type="text" name="phone"  maxlength="12" id="id_phone">

    </div>

    <div>
    <label for="id_address">Address:</label>



    <input type="text" name="address"  maxlength="12" id="id_address">

    </div>

    <div>
    <label for="id_profile_image">Profile image:</label>



    <input type="file" name="profile_image" accept="image/*" id="id_profile_image">



    </div>
                  <button type="submit" class="btn btn-success btn-block">Update</button>
                </form>
                <hr>
                <div class="text-center">
                  <a class="small" href="/profile/">Profile</a>
                  <a class="small" href="/home/">Back</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>



    </div>
    <!-- /.container-fluid -->
  
</body>

{% endblock %}